version: "3.7"

services:
  challenges_ignite:
    image: postgres
    container_name: challenges_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=renato
      - POSTGRES_PASSWORD=re@123
      - POSTGRES_DB=finapi
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: ignite
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - challenges_ignite
    depends_on:
      - challenges_ignite

volumes:
  pgdata:
    driver: local
